### ISSUE TITLE
词向量文件找不到，FileNotFoundError: [Errno 2] No such file or directory: './data/demo/w2v.pkl'

### ISSUE THREAD

**Issue by yanqiangmiffy** [zsctju/triplets-extraction#3]
`FileNotFoundError: [Errno 2] No such file or directory: './data/demo/w2v.pkl'`
请问这个文件是在代码运行时，可以生成，还是已经训练好可以下载的？

**Comment by topgunforone** [comment]
我也是没有找到词向量，NYT数据的词向量是txt格式，我转成pkl后仍然不行，请问您解决了么

**Comment by yanqiangmiffy** [comment]
@topgunforone 这个需要自己将nYT的词向量txt格式转为pkl

**Comment by codeants2012** [comment]
请问NYT的词向量在哪儿找？@yanqiangmiffy

**Comment by vivien-moo** [comment]
@yanqiangmiffy 意思是需要自己写代码将nyt的词向量转换为txt格式嘛？

**Comment by yanqiangmiffy** [comment]
@vivien-moo 是的，

**Comment by yanqiangmiffy** [comment]
https://github.com/shanzhenren/CoType

**Comment by yanqiangmiffy** [comment]
**另外代码中的文件路径要改下**

**Comment by xxrQiu** [comment]
@yanqiangmiffy 请问您知道./data/demo/train_tag.json这个文件是在哪里吗

**Comment by xxrQiu** [comment]
@yanqiangmiffy 请问您./data/demo/w2v.pkl这个问题现在已经解决了吗

**Comment by yanqiangmiffy** [comment]
@xxrQiu 解决了

**Comment by yanqiangmiffy** [comment]
词向量文件，比较大，可以加我qq：1185918903

**Comment by baiyue12138** [comment]
@yanqiangmiffy 可不可以分享下词向量文件？

**Comment by yanqiangmiffy** [comment]
这个是文件目录，缺什么`文件夹`，就建什么，然后文件的话运行程序会自动生成；
![](https://upload-images.jianshu.io/upload_images/1531909-b19b73c57fcd3f9d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
这个词向量文件：我上传到网盘了 加qq有点麻烦了。链接：https://share.weiyun.com/5k8sHki 密码：2mkmh9

**Comment by LCabbage** [comment]
@yanqiangmiffy 你好，我按你说的建了缺失的文件，在运行时显示EOFError: Ran out of input。你遇到这个问题了吗，是因为是空文件吗，请问怎么解决？谢谢！

**Comment by LCabbage** [comment]
@yanqiangmiffy 您好，请问您有没有在TaggingScheme.py遇到下面这个问题：
Traceback (most recent call last):
  File "D:/WorkSpace/PythonSpace/triplets-extraction-master/TaggingScheme.py", line 283, in tag_sent
    train_json_file.write(json.dumps(newsent)+'\n')
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/WorkSpace/PythonSpace/triplets-extraction-master/TaggingScheme.py", line 319, in <module>
    tag_sent(infile3,infile4,isTrain=False)
  File "D:/WorkSpace/PythonSpace/triplets-extraction-master/TaggingScheme.py", line 285, in tag_sent
    print (e.message, e.args)
AttributeError: 'TypeError' object has no attribute 'message'

找了一些解决方法，都不行，请指教！谢谢！

**Comment by JewelYueng** [comment]
@yanqiangmiffy 您好，想要请问一下怎么生成那个train_tag.json文件，万分感谢！

**Comment by weizhepei** [comment]
> @yanqiangmiffy 您好，请问您有没有在TaggingScheme.py遇到下面这个问题：
> Traceback (most recent call last):
> File "D:/WorkSpace/PythonSpace/triplets-extraction-master/TaggingScheme.py", line 283, in tag_sent
> train_json_file.write(json.dumps(newsent)+'\n')
> TypeError: a bytes-like object is required, not 'str'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "D:/WorkSpace/PythonSpace/triplets-extraction-master/TaggingScheme.py", line 319, in 
> tag_sent(infile3,infile4,isTrain=False)
> File "D:/WorkSpace/PythonSpace/triplets-extraction-master/TaggingScheme.py", line 285, in tag_sent
> print (e.message, e.args)
> AttributeError: 'TypeError' object has no attribute 'message'
> 
> 找了一些解决方法，都不行，请指教！谢谢！

改一下试试： e.message --> e.\_\_context\_\_

**Comment by SeekPoint** [comment]
nYT的词向量 怎么来的，能详细说明一下吗

**Comment by yanqiangmiffy** [comment]
> nYT的词向量 怎么来的，能详细说明一下吗

https://github.com/shanzhenren/CoType
